# Generated by Django 5.2.10 on 2026-01-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_hotelrecommendation_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrecommendation',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelrecommendation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
